# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToTokGameDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToTokGameDemo
  pod 'ToTokGameSDK'
  pod 'SDWebImage'

end
