# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToTokGameDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToTokGameDemo
  pod 'TTkGameSDK'
  pod 'SDWebImage'
#  pod 'FBSDKCoreKit' , '5.13.1'
#  pod 'FBSDKLoginKit' , '5.13.1'
#  pod 'FBSDKShareKit' , '5.13.1'

end
